### ISSUE TITLE
Missing EPSG code for Vietnam (EPSG::9205	to EPSG::9218)

### ISSUE THREAD

**Issue by thangqd** [maptiler/epsg.io#155]
Dear epsg.io Team! 
I've added some Vietnam Projections to the latest version 9.8 (9.8.2) of EPSG database (2019-09-19)
You can check it: http://www.epsg-registry.org/ and Search "vn-2000"
I understand that you have updated the latest version of EPSG Database in #150 
But when I go to http://epsg.io/?q=vn-2000, I can't see the Projections of Vietnam that I have added
Please check and let me know could I have some further steps to cooperate with epsg.io team to update these projections. Thank you!

**Comment by daliborjanak** [comment]
Thanks for the ticket. We updated the code but we didn't deploy it yet - we have some problem with deployment which will be solved soon, I hope.
