### ISSUE TITLE
Endpoints now throwing 500 errors

### ISSUE THREAD

**Issue by greglucas** [maptiler/epsg.io#156]
Endpoints that were previously working a few days ago are now returning 500 responses.
See: https://github.com/rhattersley/pyepsg/issues/15 and https://github.com/SciTools/cartopy/issues/1437

Is there a new endpoint that should be used with the `urn:ogc:def:area:EPSG::3544` request?

It looks like this could be the same as this older issue https://github.com/maptiler/epsg.io/issues/89, but this is a very recent change.

**Comment by daliborjanak** [comment]
We noticed that. We will deploy the fixed version soon. Thanks for the report

**Comment by evankielley** [comment]
Any update on this @TomPohys ? I have a running service that is down because it depends on this fix

**Comment by wbeirigo** [comment]
Is there some turnaround, for running service?

**Comment by klokan** [comment]
@TomPohys works on this now - it should be fixed and deployed really soon.

**Comment by evankielley** [comment]
Awesome, thank you all!

**Comment by wbeirigo** [comment]
Hope this version go to production fast.

**Comment by greglucas** [comment]
It is still erroring for me...
http://epsg.io/urn:ogc:def:area:EPSG::3544.gml?download

Is it fixed locally and just not deployed to production?

**Comment by daliborjanak** [comment]
Deployed, now it works
