### ISSUE TITLE
internet explorer 11

### ISSUE THREAD

**Issue by corteza10** [maptiler/epsg.io#157]
Hello,

We're having some issues since last Week with the epsg.io website (https://epsg.io/) in our computer with internet explorer 11. In this explorer version the screen freezes and it's not possible to move or zoom the map. It's not an option for me to install another webrowser.

When we use the emulator option (F12) with version 10 it works well. But I couldn't find any way to fix this option as defaut option. 

<a href="https://imgur.com/q2nw1CQ"><img src="https://i.imgur.com/q2nw1CQ.jpg" title="source: imgur.com" /></a>

Any idea or advice in orther to solve this probleme?

**Comment by corteza10** [comment]
more info with the debugger:

<a href="https://imgur.com/eAMFKEi"><img src="https://i.imgur.com/eAMFKEi.jpg" title="source: imgur.com" /></a>

**Comment by corteza10** [comment]
More info with the debugger :

<a href="https://imgur.com/eAMFKEi"><img src="https://i.imgur.com/eAMFKEi.jpg" title="source: imgur.com" /></a>

**Comment by daliborjanak** [comment]
There is missing ClipBoard lib so I link that https://github.com/maptiler/epsg.io/commit/b13a4e1988da566e50cac40eeea69933a5bf90e3
I hope it will fix that we will see after deploy. Thanks for the report

**Comment by corteza10** [comment]
Thank you. It's the new version already deployed?

**Comment by daliborjanak** [comment]
Not yet. We need to do more fixes #158 and #156 
We will deploy those tickets together
