### ISSUE TITLE
Get the source of coordinate system information

### ISSUE THREAD

**Issue by lovesL** [maptiler/epsg.io#184]
hi, man, `https://epsg.io/?format=json&q=${ coord }`, what parameters do I need to add to get whether this coordinate system is EPSG or ESRI
![image](https://user-images.githubusercontent.com/27960630/177452052-e27f437f-8e5c-48fc-993e-a59cbc5f659d.png)
I want to get the value of this proj4js
![image](https://user-images.githubusercontent.com/27960630/177452962-d6d56d7c-460d-4069-b921-e2943ace6b70.png)

**Comment by lovesL** [comment]
Is this project still under maintenance?

**Comment by AliFlux** [comment]
Hi, yes the project is still under maintenance.

Currently there's no way to get information source from existing APIs. In future the APIs will be updated and this support will be added

**Comment by lovesL** [comment]
OK, I hope to support it as soon as possible, I am waiting to use it, thank you

**Comment by zhaobao1830** [comment]
I am also waiting for this feature

**Comment by ydl602010338** [comment]
Big Wolf also waiting for this feature

**Comment by AliFlux** [comment]
Hi, please confirm if you can access the authority info in the API update. There is a new authority parameter (ESRI, EPSG).

https://epsg.io/?format=json&q=54004
