### ISSUE TITLE
Page returns 200 HTTP code despite encountering an error

### ISSUE THREAD

**Issue by rdewit** [maptiler/epsg.io#188]
When looking up the projection details for a code that does not exist, the user receives a HTML page containing the error code and text, but the actual HTTP headers return `200 OK`. 

Example: https://epsg.io/1.proj4, which returns `500: Internal Server Error` in the HTML but `200 OK` in the response headers.

This is problematic for software that tries to retrieve the information programmatically, like [OpenLayers](https://github.com/openlayers/openlayers/pull/14122).

**Comment by AliFlux** [comment]
This is fixed at epsg. https://epsg.io/1.proj4 returns 404 now

**Comment by rdewit** [comment]
Thanks @AliFlux! I'll close the issue.
